"""empty message

Revision ID: 5ee6b9c763c3
Revises: 9b939e356b42
Create Date: 2022-07-29 07:23:27.405725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee6b9c763c3'
down_revision = '9b939e356b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('vehicles_id', sa.Integer(), nullable=True),
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicles_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index('gender', table_name='characters')
    op.drop_index('gender_2', table_name='characters')
    op.drop_index('specie', table_name='characters')
    op.drop_index('specie_2', table_name='characters')
    op.drop_index('climate', table_name='planets')
    op.drop_index('climate_2', table_name='planets')
    op.drop_index('gravity', table_name='planets')
    op.drop_index('gravity_2', table_name='planets')
    op.drop_index('population', table_name='planets')
    op.drop_index('population_2', table_name='planets')
    op.drop_index('terrain', table_name='planets')
    op.drop_index('terrain_2', table_name='planets')
    op.drop_index('average_height', table_name='species')
    op.drop_index('average_height_2', table_name='species')
    op.drop_index('average_lifespan', table_name='species')
    op.drop_index('average_lifespan_2', table_name='species')
    op.drop_index('eye_colors', table_name='species')
    op.drop_index('eye_colors_2', table_name='species')
    op.drop_index('hair_colors', table_name='species')
    op.drop_index('hair_colors_2', table_name='species')
    op.drop_index('homewold', table_name='species')
    op.drop_index('homewold_2', table_name='species')
    op.drop_index('language', table_name='species')
    op.drop_index('language_2', table_name='species')
    op.drop_index('cost_in_credits', table_name='starships')
    op.drop_index('cost_in_credits_2', table_name='starships')
    op.drop_index('manufacturer', table_name='starships')
    op.drop_index('manufacturer_2', table_name='starships')
    op.drop_index('model', table_name='starships')
    op.drop_index('model_2', table_name='starships')
    op.drop_index('starship_class', table_name='starships')
    op.drop_index('starship_class_2', table_name='starships')
    op.drop_index('cost_in_credits', table_name='vehicles')
    op.drop_index('cost_in_credits_2', table_name='vehicles')
    op.drop_index('manufacturer', table_name='vehicles')
    op.drop_index('manufacturer_2', table_name='vehicles')
    op.drop_index('model', table_name='vehicles')
    op.drop_index('model_2', table_name='vehicles')
    op.drop_index('vehicle_class', table_name='vehicles')
    op.drop_index('vehicle_class_2', table_name='vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('vehicle_class_2', 'vehicles', ['vehicle_class'], unique=False)
    op.create_index('vehicle_class', 'vehicles', ['vehicle_class'], unique=False)
    op.create_index('model_2', 'vehicles', ['model'], unique=False)
    op.create_index('model', 'vehicles', ['model'], unique=False)
    op.create_index('manufacturer_2', 'vehicles', ['manufacturer'], unique=False)
    op.create_index('manufacturer', 'vehicles', ['manufacturer'], unique=False)
    op.create_index('cost_in_credits_2', 'vehicles', ['cost_in_credits'], unique=False)
    op.create_index('cost_in_credits', 'vehicles', ['cost_in_credits'], unique=False)
    op.create_index('starship_class_2', 'starships', ['starship_class'], unique=False)
    op.create_index('starship_class', 'starships', ['starship_class'], unique=False)
    op.create_index('model_2', 'starships', ['model'], unique=False)
    op.create_index('model', 'starships', ['model'], unique=False)
    op.create_index('manufacturer_2', 'starships', ['manufacturer'], unique=False)
    op.create_index('manufacturer', 'starships', ['manufacturer'], unique=False)
    op.create_index('cost_in_credits_2', 'starships', ['cost_in_credits'], unique=False)
    op.create_index('cost_in_credits', 'starships', ['cost_in_credits'], unique=False)
    op.create_index('language_2', 'species', ['language'], unique=False)
    op.create_index('language', 'species', ['language'], unique=False)
    op.create_index('homewold_2', 'species', ['homewold'], unique=False)
    op.create_index('homewold', 'species', ['homewold'], unique=False)
    op.create_index('hair_colors_2', 'species', ['hair_colors'], unique=False)
    op.create_index('hair_colors', 'species', ['hair_colors'], unique=False)
    op.create_index('eye_colors_2', 'species', ['eye_colors'], unique=False)
    op.create_index('eye_colors', 'species', ['eye_colors'], unique=False)
    op.create_index('average_lifespan_2', 'species', ['average_lifespan'], unique=False)
    op.create_index('average_lifespan', 'species', ['average_lifespan'], unique=False)
    op.create_index('average_height_2', 'species', ['average_height'], unique=False)
    op.create_index('average_height', 'species', ['average_height'], unique=False)
    op.create_index('terrain_2', 'planets', ['terrain'], unique=False)
    op.create_index('terrain', 'planets', ['terrain'], unique=False)
    op.create_index('population_2', 'planets', ['population'], unique=False)
    op.create_index('population', 'planets', ['population'], unique=False)
    op.create_index('gravity_2', 'planets', ['gravity'], unique=False)
    op.create_index('gravity', 'planets', ['gravity'], unique=False)
    op.create_index('climate_2', 'planets', ['climate'], unique=False)
    op.create_index('climate', 'planets', ['climate'], unique=False)
    op.create_index('specie_2', 'characters', ['specie'], unique=False)
    op.create_index('specie', 'characters', ['specie'], unique=False)
    op.create_index('gender_2', 'characters', ['gender'], unique=False)
    op.create_index('gender', 'characters', ['gender'], unique=False)
    op.drop_table('favorites')
    # ### end Alembic commands ###
