"""empty message

Revision ID: 71ffa56f18b0
Revises: 4d0218e1d82d
Create Date: 2022-07-31 07:08:36.379179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71ffa56f18b0'
down_revision = '4d0218e1d82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('homeworld', sa.String(length=20), nullable=False))
    op.drop_column('species', 'homewold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('homewold', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('species', 'homeworld')
    # ### end Alembic commands ###
