"""empty message

Revision ID: fd83fa353cc1
Revises: 5ee6b9c763c3
Create Date: 2022-07-29 08:51:10.861124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd83fa353cc1'
down_revision = '5ee6b9c763c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='favorites')
    op.drop_index('user_id_2', table_name='favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id_2', 'favorites', ['user_id'], unique=False)
    op.create_index('user_id', 'favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###
